// Copyright (c) Dualsoft  All Rights Reserved.
namespace Engine.Core

open System.Collections.Generic
open System
open System.Linq
open Engine.Common
open Dual.Common.Base.FS
open Dual.Common.Core.FS

[<AutoOpen>]
module Interface =
    type IText  =
        abstract ToText: unit -> string

    type IType =
        abstract DataType : System.Type


    type IValue =
        abstract ObjValue: obj with get  // Renamed from 'BoxedValue' to avoid confusion

    /// 예지 보전 관련 정보.
    type IMainenance = interface end

    type IStorage =
        inherit IValue
        inherit INamed
        inherit IText
        inherit IType
        inherit IComparable
        abstract Address: string with get, set
        abstract DsSystem: ISystem
        abstract Target: IQualifiedNamed option
        abstract TagKind: int
        abstract TagChanged: bool with get, set
        abstract BoxedValue: obj with get, set
        abstract IsGlobal: bool with get, set
        abstract IsAutoGenerated: bool with get, set
        abstract Comment: string with get, set
        abstract ToBoxedExpression: unit -> obj
        abstract MaintenanceInfo: IMainenance option with get, set

    and ISystem =
        inherit IVertex

    type ITerminal =
        abstract Variable: IStorage option
        abstract Literal: IExpressionizableTerminal option

    and IExpressionizableTerminal =
        inherit IText
        inherit IType
        inherit ITerminal

    // Collections and Managers
    type Storages() =
        inherit Dictionary<string, IStorage>(StringComparer.OrdinalIgnoreCase)
        new (existing:Storages) =
            Storages() then        // constructor chaning
            for kv in existing do
                base.Add(kv.Key, kv.Value)

    /// obsidian 문서 : DsDotNet/src/Doc/Obsidian/DS/Engine.Core/ITagManager.canvas 참고
    type ITagManager =
        abstract Target: IQualifiedNamed
        abstract Storages: Storages

    // Utilities
    let inline address x = ( ^T: (member Address: string) x )
