// Copyright (c) Dual Inc.  All Rights Reserved.
namespace Engine.Core

open System.Collections.Generic
open System

[<AutoOpen>]
module Interface =

    // Basic interfaces
    type IVertex = interface end

    type INamed  =
        abstract Name: string with get, set

    type IText  =
        abstract ToText: unit -> string

    type IType =
        abstract DataType : System.Type


    type IValue =
        abstract ObjValue: obj with get  // Renamed from 'BoxedValue' to avoid confusion

    // Extended interfaces
    type IQualifiedNamed =
        inherit INamed
        abstract QualifiedName: string with get
        abstract NameComponents: string[] with get

    type IStorage =
        inherit IValue
        inherit INamed
        inherit IText
        inherit IType
        inherit IComparable
        abstract Address: string with get, set
        abstract DsSystem: ISystem
        abstract Target: IQualifiedNamed option
        abstract TagKind: int
        abstract TagChanged: bool with get, set
        abstract BoxedValue: obj with get, set
        abstract IsGlobal: bool with get, set
        abstract IsAutoGenerated: bool with get, set
        abstract Comment: string with get, set
        abstract ToBoxedExpression: unit -> obj

    and ISystem = interface end

    type IExpressionizableTerminal =
        inherit IText
        inherit IType

    type ITerminal =
        abstract Variable: IStorage option
        abstract Literal: IExpressionizableTerminal option

    // Collections and Managers
    type Storages() =
        inherit Dictionary<string, IStorage>(StringComparer.OrdinalIgnoreCase)

    type ITagManager =
        abstract Target: IQualifiedNamed
        abstract Storages: Storages

    // Utilities
    let inline address x = ( ^T: (member Address: string) x )

    type ITerminal with
        member x.GetContact(): string =
            match x.Variable, x.Literal with
            | Some v, None -> v.Name
            | None, Some literal -> literal.ToText()
            | _ -> failwith "Invalid terminal"
