//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Resources;

namespace Dual.Common.Resources.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dual.Common.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A {
            get {
                object obj = ResourceManager.GetObject("A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActionAdd {
            get {
                object obj = ResourceManager.GetObject("ActionAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActionCancel {
            get {
                object obj = ResourceManager.GetObject("ActionCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowBackward {
            get {
                object obj = ResourceManager.GetObject("ArrowBackward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowBackwardGreen {
            get {
                object obj = ResourceManager.GetObject("ArrowBackwardGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDownGreen {
            get {
                object obj = ResourceManager.GetObject("ArrowDownGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDownSlimBlue {
            get {
                object obj = ResourceManager.GetObject("ArrowDownSlimBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDownSlimRed {
            get {
                object obj = ResourceManager.GetObject("ArrowDownSlimRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowForward {
            get {
                object obj = ResourceManager.GetObject("ArrowForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowForwardGreen {
            get {
                object obj = ResourceManager.GetObject("ArrowForwardGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUpDownSlimBlue {
            get {
                object obj = ResourceManager.GetObject("ArrowUpDownSlimBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUpDownSlimRed {
            get {
                object obj = ResourceManager.GetObject("ArrowUpDownSlimRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUpSlimBlue {
            get {
                object obj = ResourceManager.GetObject("ArrowUpSlimBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUpSlimRed {
            get {
                object obj = ResourceManager.GetObject("ArrowUpSlimRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Camera {
            get {
                object obj = ResourceManager.GetObject("Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Converter {
            get {
                object obj = ResourceManager.GetObject("Converter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Empty {
            get {
                object obj = ResourceManager.GetObject("Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EventBlue {
            get {
                object obj = ResourceManager.GetObject("EventBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Finish {
            get {
                object obj = ResourceManager.GetObject("Finish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FinishRed {
            get {
                object obj = ResourceManager.GetObject("FinishRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FullScreen {
            get {
                object obj = ResourceManager.GetObject("FullScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightGreen {
            get {
                object obj = ResourceManager.GetObject("LightGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightRed {
            get {
                object obj = ResourceManager.GetObject("LightRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightYellow {
            get {
                object obj = ResourceManager.GetObject("LightYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Log {
            get {
                object obj = ResourceManager.GetObject("Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MediaPause {
            get {
                object obj = ResourceManager.GetObject("MediaPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MediaPlay {
            get {
                object obj = ResourceManager.GetObject("MediaPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MediaPlayGreen {
            get {
                object obj = ResourceManager.GetObject("MediaPlayGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MediaStepForward {
            get {
                object obj = ResourceManager.GetObject("MediaStepForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MediaStop {
            get {
                object obj = ResourceManager.GetObject("MediaStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MediaStopRed {
            get {
                object obj = ResourceManager.GetObject("MediaStopRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewWindow {
            get {
                object obj = ResourceManager.GetObject("NewWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Person {
            get {
                object obj = ResourceManager.GetObject("Person", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pin {
            get {
                object obj = ResourceManager.GetObject("Pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Property {
            get {
                object obj = ResourceManager.GetObject("Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robot {
            get {
                object obj = ResourceManager.GetObject("Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Script {
            get {
                object obj = ResourceManager.GetObject("Script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScriptApp {
            get {
                object obj = ResourceManager.GetObject("ScriptApp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScriptDoc {
            get {
                object obj = ResourceManager.GetObject("ScriptDoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScriptSmall {
            get {
                object obj = ResourceManager.GetObject("ScriptSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Simulator {
            get {
                object obj = ResourceManager.GetObject("Simulator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartRed {
            get {
                object obj = ResourceManager.GetObject("StartRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T {
            get {
                object obj = ResourceManager.GetObject("T", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableAdd {
            get {
                object obj = ResourceManager.GetObject("TableAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableCell {
            get {
                object obj = ResourceManager.GetObject("TableCell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableColumn {
            get {
                object obj = ResourceManager.GetObject("TableColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableRow {
            get {
                object obj = ResourceManager.GetObject("TableRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Task {
            get {
                object obj = ResourceManager.GetObject("Task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tools {
            get {
                object obj = ResourceManager.GetObject("Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tools_dark {
            get {
                object obj = ResourceManager.GetObject("Tools_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeView {
            get {
                object obj = ResourceManager.GetObject("TreeView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserGroup {
            get {
                object obj = ResourceManager.GetObject("UserGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }









        internal static System.Drawing.Bitmap AND
        {
            get
            {
                object obj = ResourceManager.GetObject("AND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows4_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows4_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows4_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows4_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows4_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows5_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows5_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows5_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows5_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows5_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows5_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Arrows5_5
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrows5_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey4_1
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey4_2
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey4_3
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey4_4
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey4_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey5_1
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey5_2
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey5_3
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey5_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey5_4
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey5_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ArrowsGrey5_5
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowsGrey5_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap AxisXReverse_32
        {
            get
            {
                object obj = ResourceManager.GetObject("AxisXReverse_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Bar16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Bar16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Boxes5_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Boxes5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Boxes5_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Boxes5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Boxes5_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Boxes5_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Boxes5_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Boxes5_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Boxes5_5
        {
            get
            {
                object obj = ResourceManager.GetObject("Boxes5_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Button
        {
            get
            {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ButtonSave
        {
            get
            {
                object obj = ResourceManager.GetObject("ButtonSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ConnectOn
        {
            get
            {
                object obj = ResourceManager.GetObject("ConnectOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap DSCheck
        {
            get
            {
                object obj = ResourceManager.GetObject("DSCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap DSDiagram
        {
            get
            {
                object obj = ResourceManager.GetObject("DSDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap DS_Model_Import
        {
            get
            {
                object obj = ResourceManager.GetObject("DS_Model_Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap DashReverse_32
        {
            get
            {
                object obj = ResourceManager.GetObject("DashReverse_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap DataBinding16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("DataBinding16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap EditDummy
        {
            get
            {
                object obj = ResourceManager.GetObject("EditDummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap EditWork
        {
            get
            {
                object obj = ResourceManager.GetObject("EditWork", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Emul
        {
            get
            {
                object obj = ResourceManager.GetObject("Emul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Export
        {
            get
            {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap First_16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("First_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap First_32x32
        {
            get
            {
                object obj = ResourceManager.GetObject("First_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Flags3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Flags3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Flags3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Flags3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Flags3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Flags3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap HWIO
        {
            get
            {
                object obj = ResourceManager.GetObject("HWIO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Home_16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Home_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        internal static System.Drawing.Bitmap ListItems16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("ListItems16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Marker
        {
            get
            {
                object obj = ResourceManager.GetObject("Marker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap MediaPerformance_16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("MediaPerformance_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap MenuBar_ExportToExcel
        {
            get
            {
                object obj = ResourceManager.GetObject("MenuBar_ExportToExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Next
        {
            get
            {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Next_16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Next_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Next_32x32
        {
            get
            {
                object obj = ResourceManager.GetObject("Next_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap OR
        {
            get
            {
                object obj = ResourceManager.GetObject("OR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap OpenZip
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenZip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Options16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Options16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap OriSen
        {
            get
            {
                object obj = ResourceManager.GetObject("OriSen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Palette_16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Palette_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Pause
        {
            get
            {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Pie16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Pie16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Play
        {
            get
            {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Properties16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Properties16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Quarters5_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Quarters5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Quarters5_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Quarters5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Quarters5_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Quarters5_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Quarters5_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Quarters5_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Quarters5_5
        {
            get
            {
                object obj = ResourceManager.GetObject("Quarters5_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating4_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating4_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating4_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating4_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating4_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating5_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating5_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating5_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating5_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating5_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating5_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Rating5_5
        {
            get
            {
                object obj = ResourceManager.GetObject("Rating5_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap RedToBlack4_1
        {
            get
            {
                object obj = ResourceManager.GetObject("RedToBlack4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap RedToBlack4_2
        {
            get
            {
                object obj = ResourceManager.GetObject("RedToBlack4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap RedToBlack4_3
        {
            get
            {
                object obj = ResourceManager.GetObject("RedToBlack4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap RedToBlack4_4
        {
            get
            {
                object obj = ResourceManager.GetObject("RedToBlack4_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Search16x16
        {
            get
            {
                object obj = ResourceManager.GetObject("Search16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Settings
        {
            get
            {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Signs3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Signs3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Signs3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Signs3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Signs3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Signs3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Stars3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Stars3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Stars3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Stars3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Stars3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Stars3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Symbols23_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Symbols23_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Symbols23_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Symbols23_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Symbols23_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Symbols23_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Symbols3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Symbols3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Symbols3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Symbols3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Symbols3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Symbols3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights23_1
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights23_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights23_2
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights23_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights23_3
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights23_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights4_1
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights4_2
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights4_3
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap TrafficLights4_4
        {
            get
            {
                object obj = ResourceManager.GetObject("TrafficLights4_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Triangles3_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Triangles3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Triangles3_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Triangles3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Triangles3_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Triangles3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap about
        {
            get
            {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap addConnect
        {
            get
            {
                object obj = ResourceManager.GetObject("addConnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap addUnits
        {
            get
            {
                object obj = ResourceManager.GetObject("addUnits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap ani
        {
            get
            {
                object obj = ResourceManager.GetObject("ani", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap animation
        {
            get
            {
                object obj = ResourceManager.GetObject("animation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap connect
        {
            get
            {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap desktop
        {
            get
            {
                object obj = ResourceManager.GetObject("desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap dssim
        {
            get
            {
                object obj = ResourceManager.GetObject("dssim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap excel
        {
            get
            {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap hello
        {
            get
            {
                object obj = ResourceManager.GetObject("hello", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap helloDS
        {
            get
            {
                object obj = ResourceManager.GetObject("helloDS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap help
        {
            get
            {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Interface
        {
            get
            {
                object obj = ResourceManager.GetObject("Interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap load
        {
            get
            {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap loadOpen
        {
            get
            {
                object obj = ResourceManager.GetObject("loadOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap material_error
        {
            get
            {
                object obj = ResourceManager.GetObject("material_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap material_information
        {
            get
            {
                object obj = ResourceManager.GetObject("material_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap material_question
        {
            get
            {
                object obj = ResourceManager.GetObject("material_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap material_warning
        {
            get
            {
                object obj = ResourceManager.GetObject("material_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap offline
        {
            get
            {
                object obj = ResourceManager.GetObject("offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap online
        {
            get
            {
                object obj = ResourceManager.GetObject("online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap panel
        {
            get
            {
                object obj = ResourceManager.GetObject("panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap pc
        {
            get
            {
                object obj = ResourceManager.GetObject("pc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap plc
        {
            get
            {
                object obj = ResourceManager.GetObject("plc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap table
        {
            get
            {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap units
        {
            get
            {
                object obj = ResourceManager.GetObject("units", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap utils
        {
            get
            {
                object obj = ResourceManager.GetObject("utils", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap version
        {
            get
            {
                object obj = ResourceManager.GetObject("version", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap xlsx
        {
            get
            {
                object obj = ResourceManager.GetObject("xlsx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
