namespace Engine.Cpu

[<AutoOpen>]
module Func =
    let [<Literal>]  _add            = "+"
    let [<Literal>]  _addDouble      = "+D"
    let [<Literal>]  _addString      = "+T"
    let [<Literal>]  _sub            = "-" 
    let [<Literal>]  _subDouble      = "-D"
    let [<Literal>]  _mul            = "*" 
    let [<Literal>]  _mulDouble      = "*D"
    let [<Literal>]  _div            = "/" 
    let [<Literal>]  _divDouble      = "/D"
    let [<Literal>]  _modu           = "%" 
    let [<Literal>]  _moduDouble     = "%D"
    let [<Literal>]  _equal          = "=" 
    let [<Literal>]  _equalString    = "=T"
    let [<Literal>]  _notEqual       = "!="
    let [<Literal>]  _notEqualString = "!=T"
    let [<Literal>]  _gt             = ">" 
    let [<Literal>]  _lt             = "<" 
    let [<Literal>]  _gte            = ">="
    let [<Literal>]  _lte            = "<="
    let [<Literal>]  _logicalAnd     = "&" 
    let [<Literal>]  _logicalOr      = "|" 
    let [<Literal>]  _logicalNot     = "!" 
    let [<Literal>]  _xorBit         = "xorBit"
    let [<Literal>]  _orBit          = "orBit"
    let [<Literal>]  _andBit         = "andBit"
    let [<Literal>]  _notBit         = "notBit"
    let [<Literal>]  _shiftLeft      = "<<"
    let [<Literal>]  _shiftRight     = ">>"
    let [<Literal>]  _convertBool    = "Bool"
    let [<Literal>]  _convertInt     = "Int" 
    let [<Literal>]  _convertString  = "String"
    let [<Literal>]  _convertSingle  = "Single"
    let [<Literal>]  _convertDouble  = "Double"
    let [<Literal>]  _abs            = "abs"
    let [<Literal>]  _absDouble      = "absD"
    let [<Literal>]  _sin            = "sin"
    let [<Literal>]  _cos            = "cos"
    let [<Literal>]  _tan            = "tan"
