namespace Dsu.PLCConverter.FS
  
open XgiBaseXML
open Dsu.PLCConverter.FS.XgiSpecs

module XgiSpecial =
  

    let createXgiXml() =
        let doc = FXDocument (FXDeclaration "1.0" "UTF-8" "yes") [
            //FXComment "This document was automatically generated by a configuration script."
            FXElement "Project" [
                "Attribute"    => "3145730"
                "Version"      => "513"
                "Comment"      => ""
                "WksNodeCount" => "16"
                "GUID"         => "a48476b3-9c89-4b57-99a4-5a8f6bcc5ecd"
                // https://stackoverflow.com/questions/12130228/can-a-xml-element-contain-text-and-child-elements-at-the-same-time
                "NewProject" |> box        // 여기에 project 이름이 들어가 있는데, Mixed-content XML 문법.
                FXElement "NetworkConfiguration" [
                    FXElement "NetworkList" [
                        FXElement "Network" [
                            "Type"        =>"NETWORK ITEM:UNKNOWN"
                            "Name"        =>"기본 네트워크"
                            "NetworkType" =>""
                        ]
                    ]
                ]
                FXElement "SystemVariable" ["HMIGUID" => ""]
                FXElement "Configurations" [
                    FXElement "Configuration" [
                        "Version" => "259"
                        "Attribute" => "272119649"
                        "Comment" => ""
                        "Kind" => "1"
                        "Type" => sprintf "%s" XgiOption.CPUsID.[XgiOption.SelectCPU]//         //106 CPU-E
                        "FindGlobal" => "1"
                        "FindSymbol" => "1"
                        "Encrytption" => ""
                        "Encrytption_UDF" => ""
                        "UploadProhibit" => "75"
                        "GUID" => "e8fc95d4-bb51-4e40-a34e-4b5f820abda3"
                        "SD_UploadProhibit" => "74"
                        "SD_Password" => ""
                        "SD_MacLimit" => ""
                        "NewPLC" |> box        // Mixed-content XML 문법.
                        FXElement "Parameters" [
                            FXElement "Parameter" [
                                "Type" => "BASIC PARAMETER"
                                FXElement "XGIBasicParam" [
                                    "bp_ver"                      => "100"
                                    "head"                        => "1145128264"
                                    "size"                        => "400"
                                    "pmt_reserved1_0"             => "0"
                                    "pmt_reserved1_1"             => "0"
                                    "pmt_reserved1_2"             => "0"
                                    "pmt_reserved1_3"             => "0"
                                    "pmt_reserved1_4"             => "0"
                                    "OsVersion"                   => "1"
                                    "CPUType"                     => "43009"
                                    "STATIC_PERIOD_MODE"          => "0"
                                    "STATIC_PERIOD_TIME"          => "10"
                                    "RESTART_METHOD"              => "43521"
                                    "REMOTE_ACCESS_PERMIT"        => "43522"
                                    "RESET_DISABLE"               => "0"
                                    "O_RESET_DISABLE"             => "0"
                                    "DCLEAR_DISABLE"              => "0"
                                    "O_DCLEAR_DISABLE"            => "0"
                                    "BASIC_MOD_RESERVED_0"        => "0"
                                    "BASIC_MOD_RESERVED_1"        => "0"
                                    "BASIC_MOD_RESERVED_2"        => "0"
                                    "BASIC_MOD_RESERVED_3"        => "0"
                                    "BASIC_MOD_RESERVED_4"        => "0"
                                    "BASIC_MOD_RESERVED_5"        => "0"
                                    "BASIC_MOD_RESERVED_6"        => "0"
                                    "BASIC_MOD_RESERVED_7"        => "0"
                                    "BASIC_MOD_RESERVED_8"        => "0"
                                    "BASIC_MOD_RESERVED_9"        => "0"
                                    "SCAN_WD_TIME_0"              => "500"
                                    "SCAN_WD_TIME_1"              => "500"
                                    "SCAN_WD_TIME_2"              => "500"
                                    "SCAN_WD_TIME_3"              => "500"
                                    "STANDARD_INPUT_FILTER_TIME"  => "3"
                                    "BASIC_TIME_RESERVED_0"       => "0"
                                    "BASIC_TIME_RESERVED_1"       => "0"
                                    "BASIC_TIME_RESERVED_2"       => "0"
                                    "BASIC_TIME_RESERVED_3"       => "0"
                                    "BASIC_TIME_RESERVED_4"       => "0"
                                    "BASIC_TIME_RESERVED_5"       => "0"
                                    "BASIC_TIME_RESERVED_6"       => "0"
                                    "BASIC_TIME_RESERVED_7"       => "0"
                                    "BASIC_TIME_RESERVED_8"       => "0"
                                    "BASIC_TIME_RESERVED_9"       => "0"
                                    "BASIC_TIME_RESERVED_10"      => "0"
                                    "DEBUG_OUTPUT_PARAMETER"      => "0"
                                    "ERROR_MODE_OUTPUT_PARAMETER" => "0"
                                    "RUN2STOP_OUTPUT_PARAMETER"   => "0"
                                    "STOP2RUN_OUTPUT_PARAMETER"   => "0"
                                    "ERROR_MODE_LATCH_PARAMETER"  => "0"
                                    "OUTPUT_PARAMETER_RESERVED_0" => "3728"
                                    "OUTPUT_PARAMETER_RESERVED_1" => "121"
                                    "OUTPUT_PARAMETER_RESERVED_2" => "0"
                                    "OUTPUT_PARAMETER_RESERVED_3" => "0"
                                    "OUTPUT_PARAMETER_RESERVED_4" => "0"
                                    "SOE_RETAIN_HISTORY"          => "43544"
                                    "SOE_PARAMETER_RESERVED_0"    => "0"
                                    "SOE_PARAMETER_RESERVED_1"    => "0"
                                    "SOE_PARAMETER_RESERVED_2"    => "0"
                                    "SOE_PARAMETER_RESERVED_3"    => "0"
                                    "SOE_PARAMETER_RESERVED_4"    => "0"
                                    "RETAIN_SET_MODE"             => "43552" //사용 43552 사용안함 0
                                    "M_AREA_INIT"                 => "0"
                                    "M_AREA_SIZE_0"               => "32"
                                    "M_AREA_SIZE_1"               => "32"
                                    "M_AREA_SIZE_2"               => "32"
                                    "M_AREA_SIZE_3"               => "32"
                                    "M_AREA_LATCH1_START"         => (XgiOption.Config.LAreaStart).ToString()
                                    "M_AREA_LATCH1_END"           => ((XgiOption.Config.LAreaStart) + XgiOption.Config.LAreaCount).ToString()
                                    "BASIC_RETAIN_RESERVED_0"     => "0"
                                    "BASIC_RETAIN_RESERVED_1"     => "0"
                                    "BASIC_RETAIN_RESERVED_2"     => "0"
                                    "BASIC_RETAIN_RESERVED_3"     => "0"
                                    "BASIC_RETAIN_RESERVED_4"     => "0"
                                    "BASIC_RETAIN_RESERVED_5"     => "0"
                                    "BASIC_RETAIN_RESERVED_6"     => "0"
                                    "BASIC_RETAIN_RESERVED_7"     => "0"
                                    "BASIC_RETAIN_RESERVED_8"     => "0"
                                    "BASIC_RETAIN_RESERVED_9"     => "0"
                                    "BASIC_RETAIN_RESERVED_10"    => "0"
                                    "BASIC_RETAIN_RESERVED_11"    => "0"
                                    "BASIC_RETAIN_RESERVED_12"    => "0"
                                    "BASIC_RETAIN_RESERVED_13"    => "0"
                                    "BASIC_RETAIN_RESERVED_14"    => "0"
                                    "BASIC_RETAIN_RESERVED_15"    => "0"
                                    "BASIC_RETAIN_RESERVED_16"    => "0"
                                    "BASIC_RETAIN_RESERVED_17"    => "0"
                                    "BASIC_RETAIN_RESERVED_18"    => "0"
                                    "BASIC_RETAIN_RESERVED_19"    => "0"
                                    "BASIC_RETAIN_RESERVED_20"    => "0"
                                    "BASIC_RETAIN_RESERVED_21"    => "0"
                                    "BASIC_RETAIN_RESERVED_22"    => "0"
                                    "BASIC_RETAIN_RESERVED_23"    => "0"
                                    "BASIC_RETAIN_RESERVED_24"    => "0"
                                    "BASIC_RETAIN_RESERVED_25"    => "0"
                                    "BASIC_RETAIN_RESERVED_26"    => "0"
                                    "BASIC_RETAIN_RESERVED_27"    => "0"
                                    "BASIC_RETAIN_RESERVED_28"    => "0"
                                    "BASIC_RETAIN_RESERVED_29"    => "0"
                                    "BASIC_RETAIN_RESERVED_30"    => "0"
                                    "BASIC_RETAIN_RESERVED_31"    => "0"
                                    "BASIC_RETAIN_RESERVED_32"    => "0"
                                    "BASIC_RETAIN_RESERVED_33"    => "0"
                                    "BASIC_RETAIN_RESERVED_34"    => "0"
                                    "BASIC_RETAIN_RESERVED_35"    => "0"
                                    "BASIC_RETAIN_RESERVED_36"    => "0"
                                    "BASIC_RETAIN_RESERVED_37"    => "0"
                                    "BASIC_RETAIN_RESERVED_38"    => "0"
                                    "BASIC_RETAIN_RESERVED_39"    => "0"
                                    "BASIC_RETAIN_RESERVED_40"    => "0"
                                    "BASIC_RETAIN_RESERVED_41"    => "0"
                                    "BASIC_RETAIN_RESERVED_42"    => "0"
                                    "BASIC_RETAIN_RESERVED_43"    => "0"
                                    "BASIC_RETAIN_RESERVED_44"    => "0"
                                    "BASIC_RETAIN_RESERVED_45"    => "0"
                                    "BASIC_RETAIN_RESERVED_46"    => "0"
                                    "BASIC_RETAIN_RESERVED_47"    => "0"
                                    "BASIC_RETAIN_RESERVED_48"    => "0"
                                    "BASIC_RETAIN_RESERVED_49"    => "0"
                                    "TIMER_RANGE_RESERVED_0"      => "0"
                                    "TIMER_RANGE_RESERVED_1"      => "0"
                                    "TIMER_RANGE_RESERVED_2"      => "0"
                                    "TIMER_RANGE_RESERVED_3"      => "0"
                                    "TIMER_RANGE_RESERVED_4"      => "0"
                                    "TIMER_RANGE_RESERVED_5"      => "0"
                                    "TIMER_RANGE_RESERVED_6"      => "0"
                                    "TIMER_RANGE_RESERVED_7"      => "0"
                                    "TIMER_RANGE_RESERVED_8"      => "0"
                                    "TIMER_RANGE_RESERVED_9"      => "0"
                                    "TIMER_RANGE_RESERVED_10"     => "0"
                                    "TIMER_RANGE_RESERVED_11"     => "0"
                                    "TIMER_RANGE_RESERVED_12"     => "0"
                                    "TIMER_RANGE_RESERVED_13"     => "0"
                                    "TIMER_RANGE_RESERVED_14"     => "0"
                                    "TIMER_RANGE_RESERVED_15"     => "0"
                                    "CHECK_FUSE_ERROR"            => "43572"
                                    "FUSE_ERROR_MODE"             => "43573"
                                    "CHECK_IO_ERROR"              => "43574"
                                    "IO_ERROR_MODE"               => "43575"
                                    "CHECK_EXT_BASE_ERROR"        => "0"
                                    "EXT_BASE_ERROR_MODE"         => "0"
                                    "ERROR_REACTION_RESERVED_0"   => "0"
                                    "ERROR_REACTION_RESERVED_1"   => "0"
                                    "ERROR_REACTION_RESERVED_2"   => "0"
                                    "ERROR_REACTION_RESERVED_3"   => "0"
                                    "ERROR_REACTION_RESERVED_4"   => "0"
                                    "ERROR_REACTION_RESERVED_5"   => "0"
                                    "ERROR_REACTION_RESERVED_6"   => "0"
                                    "ERROR_REACTION_RESERVED_7"   => "0"
                                    "ERROR_REACTION_RESERVED_8"   => "0"
                                    "ERROR_REACTION_RESERVED_9"   => "0"
                                    "ERROR_REACTION_RESERVED_10"  => "0"
                                    "ERROR_REACTION_RESERVED_11"  => "0"
                                    "ERROR_REACTION_RESERVED_12"  => "0"
                                    "ERROR_REACTION_RESERVED_13"  => "0"
                                    "ERROR_REACTION_RESERVED_14"  => "0"
                                    "ERROR_REACTION_RESERVED_15"  => "0"
                                    "ERROR_REACTION_RESERVED_16"  => "0"
                                    "ERROR_REACTION_RESERVED_17"  => "0"
                                    "ERROR_REACTION_RESERVED_18"  => "0"
                                    "ERROR_REACTION_RESERVED_19"  => "0"
                                    "ERROR_REACTION_RESERVED_20"  => "0"
                                    "ERROR_REACTION_RESERVED_21"  => "0"
                                    "CHECK_SP_ERROR"              => "43576"
                                    "SP_ERROR_MODE"               => "43577"
                                    "CHECK_CP_ERROR"              => "43578"
                                    "CP_ERROR_MODE"               => "43579"
                                    "MODBUS_STATION"              => "63"
                                    "MODBUS_BAUDRATE"             => "4434"
                                    "MODBUS_DATABIT"              => "43592"
                                    "MODBUS_PARITY"               => "43602"
                                    "MODBUS_STOPBIT"              => "43617"
                                    "MODBUS_TRX_MODE"             => "43632"
                                    "DI_START_DEVICE_TYPE"        => "73"
                                    "DO_START_DEVICE_TYPE"        => "81"
                                    "AI_START_DEVICE_TYPE"        => "77"
                                    "AO_START_DEVICE_TYPE"        => "77"
                                    "DI_DEVICE_OFFSET"            => "0"
                                    "DO_DEVICE_OFFSET"            => "0"
                                    "AI_DEVICE_OFFSET"            => "2000"
                                    "AO_DEVICE_OFFSET"            => "4000"
                                    "pmt_reserved2_0"             => "0"
                                    "pmt_reserved2_1"             => "0"
                                    "pmt_reserved2_2"             => "0"
                                    "pmt_reserved2_3"             => "0"
                                    "pmt_reserved2_4"             => "0"
                                    "pmt_reserved2_5"             => "0"
                                    "check_sum"                   => "0"
                                    "tail"                        => "1414483782"
                                ]
                            ]
                            FXElement "Parameter" [
                                "Type" => "IO PARAMETER"
                                FXElement "Base" ["Base" => "0"; "SlotCount" => "12"]
                                FXElement "Base" ["Base" => "1"; "SlotCount" => "12"]
                                FXElement "Base" ["Base" => "2"; "SlotCount" => "12"]
                                FXElement "Base" ["Base" => "3"; "SlotCount" => "12"]
                                FXElement "Base" ["Base" => "4"; "SlotCount" => "12"]
                                FXElement "Base" ["Base" => "5"; "SlotCount" => "12"]
                                FXElement "Base" ["Base" => "6"; "SlotCount" => "12"]
                                FXElement "Base" ["Base" => "7"; "SlotCount" => "12"]
                            ]
                        ]

                        //FXElement "GlobalVariables" [
                        //    FXElement "GlobalVariable" [
                        //        FXElement "Symbols" []
                        //        FXElement "TempVar" ["Count" => "0"]
                        //        FXElement "HMIFlags" []
                        //        FXElement "DirectVarComment" ["Count" => "0"]
                        //    ]
                        //]
                        FXElement "Tasks" [
                            FXElement "Task" [
                                "Version" => "257"
                                "Type" => "0"
                                "Attribute" => "2"
                                "Kind" => "0"
                                "Priority" => "0"
                                "TaskIndex" => "0"
                                "Device" => ""
                                "DeviceType" => "0"
                                "WordValue" => "0"
                                "WordCondition" => "0"
                                "BitCondition" => "0"
                                "스캔 프로그램"  |> box        // XML 문법과는 맞지 않음.
                            ]
                        ]
                        FXElement "POU" [
                            FXElement "InsertPoint" ["Content" => "Programs"]
                            //FXElement "Programs" [
                            //    FXElement "Program" [
                            //    "Task" => "스캔 프로그램"
                            //    "LocalVariable" => "1"
                            //    "Kind" => "0"
                            //    "InstanceName" => ""
                            //    "Comment" => ""
                            //    "FindProgram" => "1"
                            //    "Encrytption" => ""
                            //    "Auto Convert"  |> box        // XML 문법과는 맞지 않음.
                            //    FXElement "Body" [
                            //        FXElement "LDRoutine" [
                            //            FXElement "InsertPoint" ["Content" => "Rungs"]
                            //            //FXElement "OnlineUploadData" ["Compressed" => "1"; "dt:dt" => "bin.base64"; "xmlns:dt" => "urn:schemas-microsoft-com:datatypes"]
                            //            ]
                            //        ]
                            //    //FXElement "InsertPoint" ["Content" => "LocalVar"]
                            //    //FXElement "LocalVar" []
                            //    FXElement "RungTable" []
                            //    ]
                            //]
                        ]

                        FXElement "GlobalVariables" [
                            FXElement "InsertPoint" ["Content" => "GlobalVariable"]
                            ]
                    ]
                ]
                //FXElement "UserDefinedMetadata" [
                //    FXElement "Address1" ["경기도 군포시 당정동"]
                //    FXElement "Postcode" ["123-456"]
                //    FXElement "Patchcode" ["1"]
                //    FXElement "Reviewdate" [DateTime.UtcNow.AddYears(1).ToString("s")]
                //]
           ]
        ]
        printXDoc doc
