global using AppHMI;
global using DevExpress.Utils.Extensions;
global using DevExpress.XtraBars;
global using DevExpress.XtraBars.Docking2010.Views;
global using DevExpress.XtraBars.Docking2010.Views.Tabbed;
global using DevExpress.XtraBars.Navigation;
global using DevExpress.XtraEditors;
global using DevExpress.XtraEditors.Controls;
global using DevExpress.XtraGrid;
global using DevExpress.XtraGrid.Views.Grid;
global using DevExpress.XtraPrinting;
global using DevExpress.XtraSplashScreen;
global using DevExpress.XtraVerticalGrid;
global using Diagram.View.MSAGL;
global using DSModeler.DocControl;
global using DSModeler.Event;
global using DSModeler.Form;
global using DSModeler.HW;
global using DSModeler.Log;
global using DSModeler.PcControl;
global using DSModeler.Tree;
global using DSModeler.Utils;
global using DSModeler.ViewDiagram;
global using DsXgComm.Monitoring;
global using Dual.Common.Core;
global using Dual.Common.Winform;
global using Engine.CodeGenCPU;
global using Engine.Core;
global using Engine.Cpu;
global using Engine.Import.Office;
global using log4net;
global using Microsoft.AspNetCore.SignalR.Client;
global using ModelHandler;
global using Server.HW.Common;
global using Server.HW.XG5K;
global using System;
global using System.Collections.Generic;
global using System.Configuration;
global using System.Diagnostics;
global using System.Drawing;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Reactive.Linq;
global using System.Reactive.Subjects;
global using System.Reflection;
global using System.Runtime.Versioning;
global using System.Threading.Tasks;
global using System.Windows.Forms;

global using static Engine.CodeGenCPU.CpuLoader;
global using static Engine.CodeGenCPU.ExportModule;
global using static Engine.Core.CoreModule;
global using static Engine.Core.DsTextProperty;
global using static Engine.Core.DsType;
global using static Engine.Core.EdgeExt;
global using static Engine.Core.ExpressionForwardDeclModule;
global using static Engine.Core.ExpressionModule;
global using static Engine.Core.Interface;
global using static Engine.Core.RuntimeGeneratorModule;
global using static Engine.Core.SystemToDsExt;
global using static Engine.Core.TagKindModule;
global using static Engine.Core.TagKindModule.TagDS;
global using static Engine.Core.TagModule;
global using static Engine.Cpu.RunTime;
global using static Engine.Import.Office.ImportPPTModule;
global using static Engine.Import.Office.ViewModule;
