// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Dual.Common.Core")]
[assembly: AssemblyProduct("lpb")]
[assembly: AssemblyDescription("LS PLC Backup System")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyConfiguration("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Dual.Common.Core";
        internal const System.String AssemblyProduct = "lpb";
        internal const System.String AssemblyDescription = "LS PLC Backup System";
        internal const System.String AssemblyVersion = "0.0.1";
        internal const System.String AssemblyFileVersion = "0.0.1";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
