namespace T

open System.IO
open log4net
open log4net.Config
open Dual.Common.Core.FS
open Engine.Core
open Engine.Parser.FS

// FsUnit/XUnit 사용법:
// https://github.com/fsprojects/FsUnit/tree/master/tests/FsUnit.Xunit.Test
// https://marnee.silvrback.com/fsharp-and-xunit-classfixture
[<AutoOpen>]
module Fixtures =

    let createTag(name, address, value) =
        let param = {
            Name = name
            Value = value
            Address = Some address
            Comment = None
            System = RuntimeDS.System
            Target = None
            TagKind = -1
            IsGlobal = false
            IsAutoGenerated = false
            AliasNames = ResizeArray<string>()
        }
        Tag(param)

    let parseText (systemRepo:ShareableSystemRepository) referenceDir text =
        ModelParser.ParseFromString(text, ParserOptions.Create4Simulation(systemRepo, referenceDir, "ActiveCpuName", None, DuNone))
