#r "System.Xml.dll"
#r "System.Xml.Linq.dll"

open System
open System.Text
open System.Xml
open System.Xml.Linq
open System.IO


//https://nbevans.wordpress.com/2015/04/15/super-skinny-xml-document-generation-with-f/
module XmlGenerator =
    let FXDeclaration version encoding standalone = XDeclaration(version, encoding, standalone)
    let FXLocalName localName namespaceName = XName.Get(localName, namespaceName)
    let FXName expandedName = XName.Get(expandedName)
    let FXDocument xdecl content = XDocument(xdecl, content |> Seq.map (fun v -> v :> obj) |> Seq.toArray)
    let FXComment (value:string) = XComment(value) :> obj
    let FXElementNS localName namespaceName content = XElement(FXLocalName localName namespaceName, content |> Seq.map (fun v -> v :> obj) |> Seq.toArray) :> obj
    let FXElement expandedName content = XElement(FXName expandedName, content |> Seq.map (fun v -> v :> obj) |> Seq.toArray) :> obj
    let FXAttributeNS localName namespaceName value = XAttribute(FXLocalName localName namespaceName, value) :> obj
    let FXAttribute expandedName value = XAttribute(FXName expandedName, value) :> obj
    let (=>) x y = FXAttribute x y


    type XDocument with
        /// Saves the XML document to a MemoryStream using UTF-8 encoding, indentation and character checking.
        member doc.Save() =
            let ms = new MemoryStream()
            use xtw = XmlWriter.Create(ms, XmlWriterSettings(Encoding = Encoding.UTF8, Indent = true, CheckCharacters = true))
            doc.Save(xtw)
            ms.Position <- 0L
            ms
    /// XDocument --> XmlDocument
    // https://stackoverflow.com/questions/1508572/converting-xdocument-to-xmldocument-and-vice-versa
    let toXmlDocument (xdoc:XDocument) =
        let xmlDocument = XmlDocument()
        use xmlReader = xdoc.CreateReader()
        xmlDocument.Load(xmlReader);
        xmlDocument

    /// XmlDocument --> XDocument
    let toXDocument (xmlDocument:XmlDocument) = XDocument.Parse(xmlDocument.OuterXml)

    let printXDoc (xdoc:XDocument) =
        let sb = new StringBuilder();
        let xmlWriterSettings =
            new XmlWriterSettings(
                Indent = true,
                OmitXmlDeclaration = true,
                IndentChars = "  ",
                NewLineChars = "\r\n",
                NewLineHandling = NewLineHandling.Replace,
                NewLineOnAttributes = true)
        let writer = XmlWriter.Create(sb, xmlWriterSettings)
        let xmlDoc = toXmlDocument xdoc
        xmlDoc.Save(writer)
        sb.ToString()

    let xdoc =
        FXDocument (FXDeclaration "1.0" "UTF-8" "yes") [
            //XComment "This document was automatically generated by a configuration script."
            FXElement "Project" [
                "Attribute"    => "3145730"
                "Version"      => "513"
                "XXX" |> box        // 여기에 project 이름이 들어가 있는데, XML 문법과는 맞지 않음.
                FXElement "NetworkConfiguration" [
                    FXElement "NetworkList" [
                        FXElement "Network" [
                            "Type"        =>"NETWORK ITEM:UNKNOWN"
                            "Name"        =>"기본 네트워크"
                            "NetworkType" =>""
                        ]
                    ]
                ]
            ]
        ]